name: Jest Integration Tests
'on':
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          cd src/
          npm install
      - name: Run Jest test
        run: |
          cd src/
          npm run test:integration
